- name: delete an instance
  gcp_compute_instance:
    state: absent
    name: "{{ item }}"
    zone: "{{ zone }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
- name: create a disk
  gcp_compute_disk:
    name: "{{ item }}-disk"
    size_gb: 20
    source_image: 'projects/ubuntu-os-cloud/global/images/family/ubuntu-2004-lts'
    zone: "{{ zone }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    scopes:
        - https://www.googleapis.com/auth/compute
    state: present
  register: disk
- name: delete an address
  gcp_compute_address:
    name: "{{ item }}-address"
    region: "{{ region }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    scopes:
        - https://www.googleapis.com/auth/compute
    state: absent
- name: create an address
  gcp_compute_address:
    name: "{{ item }}-address"
    region: "{{ region }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    scopes:
        - https://www.googleapis.com/auth/compute
    state: present
  register: address
- name: create an instance
  gcp_compute_instance:
    state: present
    name: "{{ item }}"
    machine_type: n1-standard-1
    disks:
      - auto_delete: true
        boot: true
        source: "{{ disk }}"
    network_interfaces:
      - network: null # use default
        access_configs:
          - name: 'External NAT'
            nat_ip: "{{ address }}"
            type: 'ONE_TO_ONE_NAT'
    zone: "{{ zone }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    scopes:
        - https://www.googleapis.com/auth/cloud-platform
    tags:
        items: http-server,https-server
  register: instance

- name: Wait for SSH to come up
  wait_for:
    host: "{{ address.address }}"
    port: 22
    delay: 10
    timeout: 60

- name: Add host to groupname
  add_host:
    hostname: "{{ address.address }}"
    groupname: "{{ item }}vm"
    port: "9966"
  when: item == "backend"

- name: Add host to groupname
  add_host:
    hostname: "{{ address.address }}"
    groupname: "{{ item }}vm"
  when: item != "backend"

- name: Delete from known_hosts old key
  known_hosts:
    name: "{{ address.address }}"
    state: absent
